### ISSUE TITLE
Fix issue where all targets go to invalid when a comma is entered

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#125]

**Comment by jasonxris** [comment]
This issue seems to be caused by 2 things. 

1. Opening a file doesn't trigger the diagnostics provider. 
The Diagnostics provider only triggers one the file has been edited. 

2. The Parsing probably failed, and the diagnostics couldn't find those targets or source files. However this didn't appear until the document was edited and triggered the diagnostics provider. 


We should trigger the diagnostic provider when a file is opened not just when it is changed.

Here is a log when a document with errors is opened. 
```
01:20:16.508 [pool-2-thread-1] INFO  server.BazelServices - Did Open
01:20:16.509 [pool-2-thread-1] INFO  server.BazelServices - DidOpenTextDocumentParams [
  textDocument = TextDocumentItem [
    uri = "file:///workspaces/dev/playground/examples/intellij/base/BUILD"
    languageId = "starlark"
    version = 5
    text = "....." ( I replaced this information since it contained the whole file. )
  ]
  text = null
]
```
Nothing else was logged

Log After adding a comma 
```

01:24:09.500 [pool-2-thread-1] INFO  server.BazelServices - Did Change
01:24:09.502 [pool-2-thread-1] INFO  server.BazelServices - DidChangeTextDocumentParams [
  textDocument = VersionedTextDocumentIdentifier [
    version = 6
    uri = "file:///workspaces/dev/playground/examples/intellij/base/BUILD"
  ]
  uri = null
  contentChanges = ArrayList (
    TextDocumentContentChangeEvent [
      range = null
      rangeLength = null
      text = "load(.......)  ]
  )
]
01:24:09.503 [pool-2-thread-1] INFO  server.diagnostics.DiagnosticsProvider - Handling diagnostics for params:
DiagnosticParams{client=EndpointProxy for org.eclipse.lsp4j.jsonrpc.RemoteEndpoint@736c6ca7, tracker=server.utils.DocumentTracker@6c3be8f6, uri=file:///workspaces/dev/playground/examples/intellij/base/BUILD}
01:24:09.504 [pool-2-thread-1] INFO  server.diagnostics.DiagnosticsProvider - Attempting to parse starlark file for syntax highlighting.

```

A bunch of logs of the diagnostic provider trying to verify files. It fails on source files that are not found in the worktree.

**Comment by josiahsrc** [comment]
> Opening a file doesn't trigger the diagnostics provider.
> The Diagnostics provider only triggers one the file has been edited.
> 
> The Parsing probably failed, and the diagnostics couldn't find those targets or source files. However this didn't appear until the document was edited and triggered the diagnostics provider.

This may have something to do with the document tracker. The diagnostics rely on the document tracker to have content stored on load
