### ISSUE TITLE
Setup CI (GitHub Actions)

### ISSUE THREAD

**Issue by NovaMachina** [BYU-Bazel/bazel-ls#2]
As a developer, I want to see CI setup for frontend and backend testing and deployment.
AC: CI integrates with Jest
AC: CI integrates with JUnit
AC: CI runs unit tests as part of deployment

**Comment by josiahsrc** [comment]
@loganmcbride148 @jarenm I created a PR which will add a test case for the client, so that should allow you guys to finish up this task once it gets merged in 👍  https://github.com/lucidsoftware/vscode-bazel/pull/44

The command to run tests in the client is `npm test`, which has to be run from the folder with the `package.json` file
